CREATE TABLE IF NOT EXISTS Gambia_Lgas_Districts (
    `list_lga_name` VARCHAR(15) CHARACTER SET utf8,
    `list_lga_id` INT,
    `list_lga_district_name` VARCHAR(20) CHARACTER SET utf8,
    `list_lga_district_id` INT
);
INSERT INTO Gambia_Lgas_Districts VALUES
    ('Banjul LGA',1,'Banjul Central',1),
    ('Banjul LGA',1,'Banjul North',2),
    ('Banjul LGA',1,'Banjul South ',3),
    ('Basse LGA',2,'Basse Fulladu East',1),
    ('Basse LGA',2,'Jimara',2),
    ('Basse LGA',2,'Kantora',3),
    ('Basse LGA',2,'Sandu',4),
    ('Basse LGA',2,'Tumana',5),
    ('Basse LGA',2,'Wuli East',6),
    ('Basse LGA',2,'Wuli West',7),
    ('Brikama LGA',3,'Foni Bintang-Karenai',1),
    ('Brikama LGA',3,'Foni Bondali',2),
    ('Brikama LGA',3,'Foni Brefet',3),
    ('Brikama LGA',3,'Foni Jarrol',4),
    ('Brikama LGA',3,'Foni Kansala',5),
    ('Brikama LGA',3,'Kombo Central',6),
    ('Brikama LGA',3,'Kombo East',8),
    ('Brikama LGA',3,'Kombo South ',9),
    ('Janjanbureh LGA',4,'Fulladu West',1),
    ('Janjanbureh LGA',4,'Janjanbureh',2),
    ('Janjanbureh LGA',4,'Niamina Dankunku',3),
    ('Janjanbureh LGA',4,'Niamina East',4),
    ('Janjanbureh LGA',4,'Niamina West',5),
    ('Kanifing LGA',5,'Kanifing',1),
    ('Kerewan LGA',6,'Central Baddibu',1),
    ('Kerewan LGA',6,'Illiasa',2),
    ('Kerewan LGA',6,'Jokadu',3),
    ('Kerewan LGA',6,'Lower Baddibu',4),
    ('Kerewan LGA',6,'Lower Niumi',5),
    ('Kerewan LGA',6,'Sabach Sanjal',6),
    ('Kerewan LGA',6,'Upper Niumi',7),
    ('Kuntaur LGA',7,'Lower Saloum',1),
    ('Kuntaur LGA',7,'Niani',2),
    ('Kuntaur LGA',7,'Nianija',3),
    ('Kuntaur LGA',7,'Sami',4),
    ('Kuntaur LGA',7,'Upper Saloum',5),
    ('Mansakonko LGA',8,'Jarra Central',1),
    ('Mansakonko LGA',8,'Jarra East',2),
    ('Mansakonko LGA',8,'Jarra West',3),
    ('Mansakonko LGA',8,'Kiang Central',4),
    ('Mansakonko LGA',8,'Kiang East',5),
    ('Mansakonko LGA',8,'Kiang West',6);
